//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Artículos
    {
        public int id { get; set; }
        [Required]
        public string nombre { get; set; }

        [Required]
        public string descripción { get; set; }

        [Required(ErrorMessage ="El campo Marca debe ser usado")] 
        [Display(Name = "Marca")]
        public string marca { get; set; }

        [Required]
        public Nullable<decimal> precio { get; set; }

        [Required]
        public string stock { get; set; }
    }
}
